// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/MonsterState.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protos/MonsterState.proto</summary>
public static partial class MonsterStateReflection {

  #region Descriptor
  /// <summary>File descriptor for protos/MonsterState.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MonsterStateReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chlwcm90b3MvTW9uc3RlclN0YXRlLnByb3RvIkYKDE1vbnN0ZXJTdGF0ZRIU",
          "Cgxtb25zdGVyX25hbWUYASABKAkSDwoHeF9jb29yZBgCIAEoBRIPCgd5X2Nv",
          "b3JkGAMgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MonsterState), global::MonsterState.Parser, new[]{ "MonsterName", "XCoord", "YCoord" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MonsterState : pb::IMessage<MonsterState>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MonsterState> _parser = new pb::MessageParser<MonsterState>(() => new MonsterState());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MonsterState> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MonsterStateReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MonsterState() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MonsterState(MonsterState other) : this() {
    monsterName_ = other.monsterName_;
    xCoord_ = other.xCoord_;
    yCoord_ = other.yCoord_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MonsterState Clone() {
    return new MonsterState(this);
  }

  /// <summary>Field number for the "monster_name" field.</summary>
  public const int MonsterNameFieldNumber = 1;
  private string monsterName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MonsterName {
    get { return monsterName_; }
    set {
      monsterName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "x_coord" field.</summary>
  public const int XCoordFieldNumber = 2;
  private int xCoord_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int XCoord {
    get { return xCoord_; }
    set {
      xCoord_ = value;
    }
  }

  /// <summary>Field number for the "y_coord" field.</summary>
  public const int YCoordFieldNumber = 3;
  private int yCoord_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int YCoord {
    get { return yCoord_; }
    set {
      yCoord_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MonsterState);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MonsterState other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MonsterName != other.MonsterName) return false;
    if (XCoord != other.XCoord) return false;
    if (YCoord != other.YCoord) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MonsterName.Length != 0) hash ^= MonsterName.GetHashCode();
    if (XCoord != 0) hash ^= XCoord.GetHashCode();
    if (YCoord != 0) hash ^= YCoord.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MonsterName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(MonsterName);
    }
    if (XCoord != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(XCoord);
    }
    if (YCoord != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(YCoord);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MonsterName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(MonsterName);
    }
    if (XCoord != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(XCoord);
    }
    if (YCoord != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(YCoord);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MonsterName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MonsterName);
    }
    if (XCoord != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(XCoord);
    }
    if (YCoord != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(YCoord);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MonsterState other) {
    if (other == null) {
      return;
    }
    if (other.MonsterName.Length != 0) {
      MonsterName = other.MonsterName;
    }
    if (other.XCoord != 0) {
      XCoord = other.XCoord;
    }
    if (other.YCoord != 0) {
      YCoord = other.YCoord;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          MonsterName = input.ReadString();
          break;
        }
        case 16: {
          XCoord = input.ReadInt32();
          break;
        }
        case 24: {
          YCoord = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          MonsterName = input.ReadString();
          break;
        }
        case 16: {
          XCoord = input.ReadInt32();
          break;
        }
        case 24: {
          YCoord = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
